django-authentication-master/chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('chat', views.chat, name='chat'),
    path('chat2/', views.chat, name='chat2'),
    path('chat_sender/', views.chat_sender, name='chat_sender'),
    path('fetch/', views.fetch, name='fetch'),
    path('room/', views.room, name='room'),
    path('selectRoom/', views.selectRoom, name='selectRoom')

]

django-authentication-master/forum/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import forumhome, PostDetail, Addpost, trys, my_post, editpost, deletepost, LikeView, CommentView, \
    search_titles, forumcategories, forumcategroieseach, my_profile, user_image_view, editprofile, CommentDelete, \
    pinpost, unpinpost, acceptpost, rejectpost, typeofposts, acceptappeal, rejectappeal, replyDelete, editcomment, \
    editreply, readnotification, clearall

app_name = 'forums'
urlpatterns = [
    path('forum/categories', forumcategories, name="forumcategroies"),
    path('forum/categories/<slug:slug>', forumcategroieseach.as_view(), name="forumcategroieseach"),
    path('forum/pin/<int:pk>', pinpost, name="forumpinpost"),
    path('forum/accept/<int:pk>', acceptpost, name="forumacceptpost"),
    path('forum/reject/<int:pk>', rejectpost, name="forumrejectpost"),
    path('forum/acceptappeal/<int:pk>', acceptappeal, name="acceptappeal"),
    path('forum/rejectappeal/<int:pk>', rejectappeal, name="rejectappeal"),
    path('polls/<str:posttype>', typeofposts, name="typeofposts"),
    path('forum/unpin/<int:pk>', unpinpost, name="forumunpinpost"),
    path('forum/', trys, name='forum'),
    path('forum/my_posts', my_post, name='my_post'),
    path('forum/my_profile/', my_profile, name='my_profile'),
    path('forum/<int:pk>', PostDetail.as_view(), name='Post_detail'),
    path('forum/forum_create/', Addpost, name='create_forum'),
    path('forum/my_posts/edit/<int:pk>/', editpost, name='editpost'),
    path('forum/my_posts/read/<int:pk>/', readnotification, name='readnotification'),
    path('forum/my_posts/delete/<int:pk>/', deletepost, name='deletepost'),
    path('forum/like/<int:pk>', LikeView, name='like_post'),
    path('forum/comment/<int:pk>', CommentView, name='Comment_post'),
    path('forum/comment/edit/<int:pk>', editcomment, name='editcomment'),
    path('forum/comment/delete/<int:pk>', CommentDelete, name='CommentDelete'),
    path('forum/reply/delete/<int:pk>', replyDelete, name='replyDelete'),
    path('forum/reply/edit/<int:pk>', editreply, name='editreply'),
    path('forum/search', search_titles, name='search_post'),
    path('forum/clearall', clearall, name='clearall'),
    path('forum/my_profile/uploadimage', user_image_view, name='user_image_view'),
    path('forum/my_profile/editprofile', editprofile, name='editprofile'),
    # path('forum/comment/reply', add_reply_to_comment, name='reply_comment'),

]

django-authentication-master/home/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import game, terms, privacy, leaderboards, contact, contactus, emaillist, unsubscribe, unsubscribebtn, about

urlpatterns = [
    path('', game, name="game"),
    path('/emailnews/', emaillist, name="emailnews"),
    path('/unsubscribe/', unsubscribe, name="unsubscribe"),
    path('/unsubscribe/unsubscribebtn', unsubscribebtn, name="unsubscribebtn"),
    path('/terms/', terms, name="terms"),
    path('/privacy/', privacy, name="privacy"),
    path('/leaderboards/', leaderboards, name="leaderboards"),
    path('/contact-us/', contact, name="contact"),
    path('/about-us/', about, name="about"),
    path('/contact-us/sendmessage/', contactus, name="contactsendmsg"),
]

django-authentication-master/staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    path('staff/', views.baseview, name="baseview"),
    path('staff/users/', views.staffusers, name="staffusers.css"),
    path('staff/topics/', views.stafftopics, name="stafftopics"),
    path('staff/topics/create', views.stafftopicscreate, name="stafftopicscreate"),
    path('staff/topics/delete/<int:pk>/', views.stafftopicsdelete, name="stafftopicsdelete"),
    path('staff/topics/undo/<int:pk>/', views.stafftopicsundo, name="stafftopicsundo"),
    path('staff/topics/edit/<int:pk>/', views.stafftopicsedit, name="stafftopicsedit"),
    path('staff/subtopics/', views.staffsubtopics, name="staffsubtopics"),
    path('staff/subtopics/create', views.staffsubtopicscreate, name="staffsubtopicscreate"),
    path('staff/subtopics/delete/<int:pk>/', views.staffsubtopicsdelete, name="staffsubtopicsdelete"),
    path('staff/subtopics/undo/<int:pk>/', views.staffsubtopicsundo, name="staffsubtopicsundo"),
    path('staff/subtopics/edit/<int:pk>/', views.staffsubtopicsedit, name="staffsubtopicsedit"),
    path('staff/posts/', views.staffposts, name="staffposts"),
    path('staff/users/updaterank/<int:pk>/', views.updaterank, name="updaterank"),
    path('staff/compose', views.compose, name="compose"),
    # path('staff/users/<int:pk>/', views.useractions.as_view(), name="useractions"),
    path('staff/ban/<int:pk>/', views.banuser, name="banuser"),
    path('staff/posts/<int:pk>/', views.Detailmanageposts.as_view(), name="Detailmanageposts"),
    path('staff/kick/<int:pk>/', views.kickuser, name="kickuser"),
    path('staff/users/<int:pk>/', views.userprofile, name="userprofile"),
    path('staff/unban/<int:pk>/', views.unbanuser, name="unbanuser"),
    path('staff/posts/close/<int:pk>/', views.closepost, name="closeposts"),
    path('staff/posts/open/<int:pk>/', views.openpost, name="openposts"),
    path('staff/posts/delete/<int:pk>/', views.deletepost, name="deleteposts"),
    path('staff/posts/undo/<int:pk>/', views.staffpostsundo, name="undoposts"),
    path('staff/posts/like/<int:pk>', views.LikeView, name='like_post'),
    path('staff/contact', views.contact, name="customer_service"),
    path('staff/searchusers', views.searchusers, name="searchusers"),
    path('staff/searchposts', views.searchposts, name="searchposts"),
    path('staff/manageshop/', views.manageproducts, name="manageproducts"),
    path('staff/manageshop/editproduct/<int:pk>/', views.editproduct, name="editproduct"),
    path('staff/manageshop/deleteproduct/<int:pk>/', views.deleteproduct, name="deleteproduct"),
    path('staff/manageshop/undoproduct/<int:pk>/', views.undoproduct, name="undoproduct"),
    path('staff/manageshop/createproduct/', views.createproduct, name="createproduct"),
    path('staff/managenews/', views.managenews, name="managenews"),
    path('staff/managenews/managenewscreate', views.managenewscreate, name="managenewscreate"),
    path('staff/managenews/delete/<int:pk>/', views.newsdelete, name="newsdelete"),
    path('staff/managenews/undo/<int:pk>/', views.newsundo, name="newsundo"),
    path('staff/managenews/edit/<int:pk>/', views.newsedit, name="newsedit"),
]

django-authentication-master/chat/models.py
from django.db import models
from authapp.models import Userreg


# Create your models here.


class Room(models.Model):
    name = models.CharField(max_length=20)


class Chat(models.Model):
    uid = models.ForeignKey(Userreg, on_delete=models.CASCADE,null=False, blank=False, related_name='Userid')
    chat = models.CharField(max_length=5000)
    roomid = models.ForeignKey(Room,on_delete=models.CASCADE,null=False, blank=False, related_name='RoomId')
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date_created",)

django-authentication-master/staff/models.py
from django.db import models

# Create your models here.

django-authentication-master/forum/forms.py
from django import forms
from .models import Post, Userreg
from django.db import connection
from ckeditor.fields import RichTextField

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control ', 'type': 'text', 'name': 'title', 'placeholder': 'Type the title'}))
    body = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control  ', 'type': 'text', 'name': 'body', 'placeholder': 'Type the body'}))
    author = forms.ModelChoiceField(
        queryset=Post.objects.order_by('author').values_list('author', flat=True).distinct())

    class Meta:
        model = Post
        fields = ('title', 'body', 'author')
        widgets = {
            'make_post' : RichTextField(),
        }

django-authentication-master/chat/views.py
from django.shortcuts import render, redirect
from .models import Chat, Userreg, Room as r
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http.response import JsonResponse, HttpResponse
import json
from django.db.models import Q


def chat(request):
    obj_chat = Chat.objects.all()

    context = {
        'data1': obj_chat
    }
    return render(request, 'chat.html', context)


def chat_sender(request):
    obj_chat = Chat()
    print('this is the message--->', request.GET.get('chat'))
    print(request.session['userid'])
    chat = str(request.GET.get('chat'))
    userid = request.session['userid']
    roomid = request.session['roomId']
    obj_chat.uid = Userreg.objects.get(id=userid)
    obj_chat.chat = chat
    obj_chat.roomid = r.objects.get(id=roomid)
    obj_chat.save()
    return JsonResponse({'response': True}, safe=False)


def fetch(request):
    obj_chat = Chat.objects.filter(roomid=request.session['roomId'])

    context = {
        'data1': obj_chat
    }
    return render(request, "fetch_chat.html", context)


############################################################################################


def room(request):
    userid = request.session.get("userid")
    if userid:
        rooms = r.objects.all()
        if "room" in request.POST:
            room = r()
            room.name = request.POST["room"]
            room.save()
            return render(request, "room.html", {"room": rooms})
        return render(request, "room.html", {"room": rooms})
    else:
        return render(request, "room.html", {"room": ""})

def selectRoom(request):
    if "room" in request.POST:
        roomData = request.POST["room"].split(',')
        request.session["roomId"] = roomData[0]
        request.session["roomName"] = roomData[1]
        return redirect('/chat')

django-authentication-master/home/views.py
from datetime import datetime

from django.contrib import messages
from django.core.mail import EmailMessage, send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from humanfriendly import format_timespan

import nonmotiongame
from authapp.models import Userreg, admin_actions, Banfromgame
from authentication import settings
from home.models import emailnews, unsubscribefeedback, newsbanner

from nonmotiongame.models import GameMode_User, Rank





def game(request):
    bangame = None
    Userdetails = None
    subscribed = emailnews.objects.filter(userid=request.session.get("userid")).values('subscription')
    print(subscribed)
    scores = GameMode_User.objects.filter(Game_Mode_ID=1).order_by('-Score_Avg')[0:7]
    numbers = scores.count()
    userid=request.session.get("userid")
    bannernews = newsbanner.objects.filter(is_deleted=0)
    if request.session.get("userid"):
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
        banned = admin_actions.objects.values_list('user_ban_game', flat=True).filter(user_id=request.session.get("userid"))
        banfromforumtable = Banfromgame.objects.filter(user_id_id=request.session.get("userid"))
        for i in banfromforumtable:
            now = datetime.now()
            print(now)
            print(i.Banned_until)
            if now < i.Banned_until:
                timebangame = i.Banned_until - now
                bangame = str(
                    format_timespan(i.Banned_until - now))
        print(banned)
    print("helloworld")
    context = {"leaderboards": scores, "subscribed": subscribed, "bannernews": bannernews,"bangame":bangame, "Userdetails": Userdetails}
    return render(request, "index.html", context)


def terms(request):
    userid=request.session.get("userid")
    Userdetails = None
    if userid:
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
    context = {"Userdetails": Userdetails}
    return render(request, "Terms.html", context)

def about(request):
    userid=request.session.get("userid")
    Userdetails = None
    if userid:
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
    context = {"Userdetails": Userdetails}
    return render(request, "about.html", context)

def privacy(request):
    userid=request.session.get("userid")
    Userdetails = None
    if userid:
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
    context = {"Userdetails": Userdetails}
    return render(request, "privacy.html", context)


def leaderboards(request):
    userid=request.session.get("userid")
    Userdetails = None
    if userid:
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
    scores = GameMode_User.objects.filter(Game_Mode_ID=1).order_by('-Score_Avg')
    ranks = Rank.objects.all()
    context = {"leaderboards": scores, "Userdetails":Userdetails, "ranks":ranks}
    return render(request, "leaderboards.html", context)


def contact(request):
    userid=request.session.get("userid")
    Userdetails = None
    if userid:
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
    return render(request, "contact.html", {"Userdetails": Userdetails})


def contactus(request):
    if request.method == "POST":
        message_email = "aimarenaofficial@gmail.com"
        message = request.POST.get('message')
        message_name = request.POST.get('name')
        emailfrom = request.POST.get('email')
        print(message)
        print(message_name)
        settings.EMAIL_HOST_USER = emailfrom
        print(settings.EMAIL_HOST_USER)
        try:
            send_mail(
                'Aim Arena contact',
                message_name + '\n' + emailfrom + '\n' +
                message,
                settings.EMAIL_HOST_USER,
                [message_email],
                fail_silently=False,
            )
            messages.info(request, "Email sent successfully !")
        except:
            messages.error(request, "An unexpected error has occured, please try again later !")
        return redirect('contact')
    else:
        return redirect('contact')


def emaillist(request):
    if request.method == "POST":
        email = request.POST.get("emailnews")
        count = Userreg.objects.filter(Useremail=email, id=request.session.get("userid")).count()
        x = emailnews.objects.filter(userid=request.session.get("userid")).count()
        print(x)
        print(count)
        if count > 0:
            if x > 0:
                print("update")
                if not emailnews.objects.values_list('subscription', flat=True).get(
                        userid=request.session.get("userid")):
                    messages.info(request, "Email subscription has been updated, you will receive new mails !")
                emailnews.objects.filter(userid=request.session.get("userid")).update(subscription=True)
                message_name = "Aim Arena"
                message = "Thank you for subscribing to our newsletter ! You will receive latest updates and news of our services."
                message_email = email
                msg = EmailMessage(message_name,
                                   message,
                                   to=[message_email])
                msg.content_subtype = 'html'

                msg.send()
            else:
                new = emailnews()
                new.email = email
                new.userid = Userreg(request.session.get("userid"))
                new.subscription = True
                new.save()
                messages.info(request, "Your email is listed now, you will be notified with new news !")
        else:
            messages.error(request, "Please enter your email to be listed !")
        return redirect('game')
    else:
        return redirect('game')


def unsubscribe(request):
    userid=request.session.get("userid")
    Userdetails = None
    if userid:
        Userdetails = Userreg.objects.get(id=userid).user_thumbnail
    x = emailnews.objects.values_list('subscription', flat=True).get(
        userid=request.session.get("userid"))
    if x:
        return render(request, "unsubscribe.html", {"x": x, "Userdetails":Userdetails})
    else:
        return redirect('game')


def unsubscribebtn(request):
    if request.method == "POST":
        userid = request.session.get("userid")
        selectedvalue = request.POST.get("unsubscribe")
        message = None
        if selectedvalue == "other":
            message = request.POST.get("messagearea")

        if emailnews.objects.values_list('subscription', flat=True).get(
                userid=request.session.get("userid")):
            emailnews.objects.filter(userid=request.session.get("userid")).update(subscription=False)
            emailnewsid = emailnews.objects.get(userid=request.session.get("userid")).pk
            feedback = unsubscribefeedback()
            feedback.emailnewid = emailnews(emailnewsid)
            feedback.message = message
            feedback.feedbackname = selectedvalue
            feedback.save()
            messages.info(request, "You have been unsubscribed! thanks for your feedback")
            return redirect('unsubscribe')
        else:
            return redirect('game')
    else:
        return redirect('unsubscribe')

django-authentication-master/templates/Post_types.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Forum</title>
  <link rel="stylesheet" href="{% static 'css/Styleforum.css' %}">
  <script src="https://kit.fontawesome.com/baf7f11007.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital@1&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <style>
    #snackbar {
      visibility: hidden;
      min-width: 250px;
      margin-left: -125px;
      background-color: #333;
      color: #fff;
      text-align: center;
      border-radius: 2px;
      padding: 16px;
      position: fixed;
      z-index: 1;
      left: 50%;
      bottom: 30px;
      font-size: 17px;
    }

    #snackbar.show {
      visibility: visible;
      -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
      animation: fadein 0.5s, fadeout 0.5s 2.5s;
    }

    .dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  right: 0;
  font-size: 20px;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 3;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1;}
.dropdown:hover .dropdown-content {display: block;}
.dropdown:hover .dropbtn {background-color: #3e8e41;}


  </style>
</head>

<body>
  <header>
    <!--NavBar Section-->
    <div class="navbar">
        <nav class="navigation hide" id="navigation">
            <span class="close-icon" id="close-icon" onclick="showIconBar()"><i class="fa fa-close"></i></span>
            <ul class="nav-list">

                <li class="nav-item"><a href="{% url 'forums:forumcategroies' %}">Forums</a></li>
                <li class="nav-item"><a href="{% url 'forums:my_post' %}">My Posts</a></li>
                <li class="nav-item"><a href="{% url 'game' %}">Homepage</a></li>
            </ul>
        </nav>

        <a class="bar-icon" id="iconBar" onclick="hideIconBar()"><i class="fa fa-bars"></i></a>
      <div class="brand"><img src="{% static 'images/logo.png' %}" width="150px"/></div>


{% if request.session.Username %}




      <div class="account-info">

        <div class="dropdown" style="float:right;">
            <button class="fas fa-sort-down" style="color: #FF0042;"></button>
            <div class="dropdown-content">
              <a href="{% url 'forums:my_profile' %}">My profile</a>
              <a href="{% url 'signout' %}">Sign out</a>

            </div>
          </div>



    <img style="border-radius: 50%;" width="20px" height="20px" src="{{ Userdetails.url }}">  {{ request.session.Username }}<h5 class="account-sub">{{ request.session.Useremail }}</h5>


          {% else %}

              <div class="account-info">


                <a href="{% url 'signin' %}">Login</a> &nbsp;&nbsp;<span style="font-size: 18px;">OR</span>&nbsp;&nbsp;  <a href="{% url 'signup' %}">Register</a>  </div>


      {% endif %}

    </div>
    </div>


    </div>


    <div class="navigate header2">
      {% if ans == "reject" %}
      &nbsp; <span><a style="cursor:pointer;" onClick="javascript:history.go(-1)" ;>Forums</a> > <a>Rejected
          Posts</a></span>
      {% else %}
      &nbsp; <span><a style="cursor:pointer;" onClick="javascript:history.go(-1)" ;>Forums</a> > <a>Accepted
          Posts</a></span>
      {% endif %}
    </div>
  </header>


  <div class="container">
    <!--Navigation-->
    {% if ans == "reject" %}
    <h1><a> Total {{ count }} posts rejected by staff </a></h1>

    {% else %}

    <h1><a> Total {{ count }} posts accepted by staff </a></h1>

    {% endif %}
    <br><br>

    <!--Display posts table-->

    <div class="posts-table">
      <div class="table-head">

        <div class="subjects">&nbsp;&nbsp;Subjects</div>

      </div>
      {% for item in items %}
      <div class="table-row">

        <div class="subjects">
          <a href="{% url 'forums:Post_detail' item.id %}" class="goback">&nbsp;&nbsp;{{ item.title }}</a>
          <br>
          &nbsp;&nbsp;{{item.timestamp|timesince }} ago


        </div>

      </div>
      {% endfor %}

      <!--ends here-->
    </div>
    <!--Pagination starts-->

    <!--pagination ends-->
  </div>

  <footer id="footer">
    <span>&copy; 2021 AIMARENA. All Rights Reserved</span>
  </footer>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/forummain.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
  <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" >
  </script>

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



</body>

</html>

django-authentication-master/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>

<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %})">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
        <div class="m-b-23">
            {% if request.session.Username %}
            {% if kicked == "You were recently kicked, please behave well!" %}

		    <div class="alert alert-warning">
                <strong>Warning!</strong> {{kicked}}
            </div>
		    {% endif %}
            {% if banforum %}
              <div class="alert alert-warning">
                <strong>Warning!</strong> {{banforum}}
            </div>
            {% endif %}

                  {% if bangame %}
              <div class="alert alert-warning">
                <strong>Warning!</strong> {{bangame}}
            </div>
            {% endif %}

            <h2>Welcome {{ request.session.Username }}!</h2>

          
        </div>
        <div class="m-b-23">
            <h5><i class="far fa-user"></i>&nbsp; {{ request.session.Firstname }} {{ request.session.Lastname }}</h5>
        
        </div>
        <div class="m-b-23">
            <h5><i class="far fa-envelope-open"></i>&nbsp;&nbsp;{{ request.session.Useremail }}</h5>
            
        </div>
        <div class="m-b-23">
            <a href="{% url 'signout' %}" class="btn btn-primary">Logout</a>
            
        </div>
         <div id="counter" class="m-b-23 text-center">
             You will be redirected in 5
         </div>
    </div>

    {% endif %}
</div>
<script>

var counter = 5;
var interval = setInterval(function() {
    counter--;
    $("#counter").text("You will be redirected in "+counter);
    // Display 'counter' wherever you want to display it.
    if (counter == 1) {
    var url ;
        {% if role == "User" %}
             url = "{% url 'game' %}";
         {% else %}
            url = "{% url 'staff:baseview' %}"
         {% endif %}
        window.location = url;
        clearInterval(interval);

    }
}, 1000);


</script>
</body>

{% endblock %}

django-authentication-master/templates/post-filter.html
{% load static %}

{% for instance in permission %}
{% if instance.manage_posts == True %}

<div class="tableposts">
    <table class="table table-striped projects">
        <thead>
            <tr>
                <th style="width: 1%">
                    #
                </th>
                <th style="width: 20%">
                    Post title
                </th>
                <th style="width: 25%">
                    Post description
                </th>
                <th style="width: 20%">
                    Post Image
                </th>

                <th style="width: 10%">
                    Username
                </th>
                <th style="width:10%">Status</th>

                <th style="width: 13%">
                </th>
                <th style="width: 17%">
                </th>

            </tr>

        </thead>
        <tbody>
            {% for obj in manageposts %}
            <tr>
                <td>
                    {{ obj.id }}
                </td>
                <td>
                    <a>
                        {{ obj.title }}
                    </a>
                    <br />
                    <small>
                        {{ obj.timestamp|timesince }}
                    </small>
                </td>

                <td>
                    {{ obj.body|safe }}
                </td>
                <td>
                    <ul class="list-inline">
                        {% if obj.thumbnail %}
                        <img style="background-color:#000;" alt="postimage" class="table-avatar"
                            src="{{ obj.thumbnail.url }}">
                        {% endif %}
                    </ul>
                </td>
                <td>
                    <a>
                        {{ obj.author.Username }}
                    </a>

                </td>
                <td>
                    {% if obj.deleted %}

                    <img width="20px" src="{% static 'images/remove.png' %}" alt="deleted">


                    {% else %}
                    <img width="20px" src="https://img.icons8.com/color/48/26e07f/ok.png" />
                    {% endif %}
                </td>
                {% if obj.deleted %}
                <td></td>
                <td id="tdundo"> <button id="undo" onclick="undopost({{obj.id}})" value="{{obj.id}}"> <a id="undourl"
                            href="{% url 'staff:undoposts' obj.id %}">Undo</a></button></td>
                {% else %}
                {% if obj.is_closed  == True %}
                <td id="tdopen"> <button id="open" onclick="openpost('{{obj.id}}')" value="{{obj.id}}"> <a id="openurl"
                            href="{% url 'staff:openposts' obj.id %}">Open Post</a></button></td>
                {% else %}
                <td id="tdclose"> <button id="close" onclick="closepost('{{obj.id}}')" value="{{obj.id}}"> <a
                            id="closeurl" href="{% url 'staff:closeposts' obj.id %}">Close Post</a></button></td>
                {% endif %}

                <td><button id="delete" onclick='deleteconfirm("{{obj.id}}", "{{obj.title}}")'
                        value="{{manage.id}}">Delete Post</button></td>
                <a style="display:none;" id="deleteurl" href="{% url 'staff:deleteposts' obj.id %}"></a>
                {% endif %}
            </tr>

            {% endfor %}
        </tbody>
    </table>

    <br>



    {% endif %}


    {% endfor %}



</div>